version: '3.7'

services:
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    volumes:
      - /usr/local/nuget/nexus-data:/nexus-data
    logging:
      driver: 'json-file'
      options:
        max-size: '10k'
        max-file: '10'
    restart: always
    ports:
      - 8091:8081
