version: '3.7'

services:
  consul1:
    image: consul:${CONSUL_VERSION}
    container_name: consul-server-1
    restart: always
    command: agent -server -bootstrap-expect=3 -bind=0.0.0.0 -client=0.0.0.0 -node=consul_server_1  -datacenter=dc1 -ui
    # environment:
    #   - CONSUL_BOOTSTRAP_EXPECT=3
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - '/usr/consul/data/server1:/consul/data'
      - '/usr/consul/config/server1:/consul/config'
    ports:
      - 8500:8500
    networks:
      - mynet
  consul2:
    image: consul:${CONSUL_VERSION}
    container_name: consul-server-2
    restart: always
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul-server-1 -node=consul_server_2  -datacenter=dc1 -ui
    # environment:
    #   - CONSUL_BOOTSTRAP_EXPECT=3
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - '/usr/consul/data/server2:/consul/data'
      - '/usr/consul/config/server2:/consul/config'
    depends_on:
      - consul-server-1
    ports:
      - 8501:8500
    networks:
      - mynet
  consul3:
    image: consul:${CONSUL_VERSION}
    container_name: consul-server-3
    restart: always
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul-server-1 -node=consul_server_3 -datacenter=dc1 -ui
    # environment:
    #   - CONSUL_BOOTSTRAP_EXPECT=3
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - '/usr/consul/data/server3:/consul/data'
      - '/usr/consul/config/server3:/consul/config'
    depends_on:
      - consul-server-1
    ports:
      - 8502:8500
    networks:
      - mynet
  consul4:
    image: consul:${CONSUL_VERSION}
    container_name: consul-client-1
    restart: always
    command: agent -retry-join=consul-server-1 -node=consul_client_1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
    # environment:
    #   - CONSUL_BOOTSTRAP_EXPECT=3
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - '/usr/consul/data/client1:/consul/data'
      - '/usr/consul/config/client1:/consul/config'
    ports:
      - 8503:8500
    depends_on:
      - consul-server-2
      - consul-server-3
    networks:
      - mynet
networks:
  mynet:
