version: '3.7'

services:
  consul1:
    image: consul:${CONSUL_VERSION}
    container_name: consul-1
    restart: always
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -bootstrap-expect=3 -node=consul-1 -datacenter=dc1 -ui
    networks:
      - mynet
  consul2:
    image: consul:${CONSUL_VERSION}
    container_name: consul-2
    restart: always
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul-1 -node=consul-2 -datacenter=dc1 -ui
    depends_on:
      - consul1
    ports:
      - 8501:8500
    networks:
      - mynet
  consul3:
    image: consul:${CONSUL_VERSION}
    container_name: consul-3
    restart: always
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul-1 -node=consul-3 -datacenter=dc1 -ui
    depends_on:
      - consul1
    ports:
      - 8501:8500
    networks:
      - mynet
  consul4:
    image: consul:${CONSUL_VERSION}
    container_name: consul-4
    restart: always
    command: agent -retry-join=consul-1 -node=ndoe4 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
    ports:
      - 8501:8500
    depends_on:
      - consul2
      - consul3
    networks:
      - mynet
networks:
  mynet:
