version: '3.7'

services:
  hx.blog.api:
    container_name: hx.blog.api
    image: registry.cn-hangzhou.aliyuncs.com/songtaojie_centos/hx.blog.api
    environment:
      - ConnectionStrings__MySqlConnectionString=Server=${DB_NAME_OR_IP};Port=${DB_PORT};Database=hxcoreblog;User ID=${DB_UID};Password=${DB_PWD};CharSet=utf8
      - ConnectionStrings__IdsConnectionString=Server=${DB_NAME_OR_IP};Port=${DB_PORT};Database=hxidentityserver;User ID=${DB_UID};Password=${DB_PWD};CharSet=utf8
    ports:
      - 5003:5003
    dns:
      - ${DNS_PROVIDER1}
      - ${DNS_PROVIDER2}
services:
  hx.identityserver.api:
    container_name: hx.identityserver.api
    image: registry.cn-hangzhou.aliyuncs.com/songtaojie_centos/hx.identityserver.api
    environment:
      - ConnectionStrings__DbType=mysql
      - ConnectionStrings__DefaultConnection=Server=${DB_NAME_OR_IP};Port=${DB_PORT};Database=hxidentityserver;User ID=${DB_UID};Password=${DB_PWD};CharSet=utf8
    ports:
      - 5002:5002
    dns:
      - ${DNS_PROVIDER1}
      - ${DNS_PROVIDER2}
