version: '3.7'

services:
  hx.proxy.nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /home/songtaojie/git/:/home/songtaojie/git/
    ports:
      - '80:80'
      - '443:443'
      - '8000:8000'
      - '8001:8001'
    dns:
      - 8.8.8.8
      - 114.114.114.114
