version: '3.7'

services:
  hx-jenkins-core:
    container_name: jenkins
    image: jenkinsci/blueocean
    ports:
      - '8080:8080'
      - '50000:50000'
    restart: always
    user: root
    volumes:
      - '/var/jenkins_home:/home/songtaojie/jenkins_home'
      - '/usr/bin/docker:/usr/bin/docker'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker-compose:/usr/local/bin/docker-compose'
    environment:
      - TZ=Asia/Shanghai
