version: '3.7'

services:
  hx.proxy.nginx:
    container_name: hx.proxy.nginx
    image: ${DOCKER_REGISTRY}/${DOCKER_REGISTRY_NAMESPACE}/hx.proxy.nginx
    volumes:
      - /home/songtaojie/git/blog-admin:/var/local/blog-admin
      - /home/songtaojie/git/blog-client:/var/local/blog-client
    ports:
      - '80:80'
      - '443:443'
      - '8000:8000'
      - '8001:8001'
    dns:
      - 8.8.8.8
      - 114.114.114.114
